[workspace]
channels = ["conda-forge"]
name = "terraform-plan-comment"
platforms = ["linux-64", "osx-64", "osx-arm64"]
requires-pixi = ">=0.58"

[dependencies]
nodejs = "=20"
pnpm = "*"

[feature.pre-commit.dependencies]
pre-commit = "*"
pre-commit-hooks = "*"
typos = "*"

[feature.terraform.dependencies]
terraform = "*"

[feature.terragrunt.target.osx-64.dependencies]
terragrunt = "*"

[feature.terragrunt.target.linux-64.dependencies]
terragrunt = "*"

[environments]
default = ["pre-commit", "terraform", "terragrunt"]
pre-commit = ["pre-commit", "terraform", "terragrunt"]
terraform = ["terraform"]
terragrunt = ["terragrunt"]
