[workspace]
channels = ["conda-forge"]
name = "terraform-plan-comment"
platforms = ["linux-64", "osx-arm64"]
requires-pixi = ">=0.58"

[dependencies]
nodejs = "=20"
pnpm = "*"

[feature.pre-commit.dependencies]
pre-commit = "*"

[feature.terraform.dependencies]
terraform = "*"

[environments]
default = ["pre-commit", "terraform"]
pre-commit = ["pre-commit", "terraform"]
terraform = ["terraform"]
